services:
  express_app:
    container_name: express_app
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    # networks:
    #   - webnet
    depends_on:
      postgres:
          condition: service_healthy
          restart: true
  postgres:
    container_name: postgres
    image: postgres:latest
    # networks:
    #   - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: db_appeals
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_appeals"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgamin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:  
      - "5050:80"
    depends_on:
      - "postgres"
# networks:
  # webnet:
volumes:
  postgres_data: